name: "Datadog Golang Action"
description: "Action used to collect events and metrics by sending them to datadog"
author: "John Costa"
inputs:
  DD_API_KEY:
    description: "Datadog Api Key"
    required: true
  DD_APP_KEY:
    description: "Datadog Api Key"
    required: true
  EVENT_TITLE:
    description: "Title of the event sent to Datadog"
    required: true
  EVENT_STATUS:
    description: "Status of the event"
    default: info
    required: false
  EVENT_TAGS:
    description: "Tags labeling the event"
    required: false
  EVENT_METRIC_NAME:
    description: "Name of the count metric associated to the event. Required only when a count metric is provided."
    required: false
  EVENT_METRIC:
    description: "Collects an integer value to report as a count metric associated to the event"
    required: false

outputs:
  output:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
