name: "Datadog Golang Action"
description: "Action used to collect events and metrics by sending them to datadog"
author: "John Costa"
inputs:
  DD_API_KEY:
    description: "Datadog Api Key"
    required: true
#outputs:
#  myOutput:
#    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
