name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: johncosta/datadog-github-action-poc@master
        with:
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_APP_KEY: ${{secrets.DD_API_KEY}}
          EVENT_TITLE: Integration Test
          EVENT_TAGS: "env=PoC, app:datadog-github-action, event:${{github.event_name}}, job:${{github.job}}"
          EVENT_METRIC_NAME: "event.datadog-github-action.${{github.event_name}}.runtime"
          EVENT_METRIC: 1

#      - name: Check outputs
#        run: |
#          test "${{ steps.selftest.outputs.myOutput }}" == "Hello"
