name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          env
          echo "$GITHUB_CONTEXT"
          echo "$SECRETS_CONTEXT"
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: johncosta/datadog-github-action-poc@master
        with:
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_APP_KEY: ${{secrets.DD_API_KEY}}
          EVENT_TITLE: Integration Test
          EVENT_TAG: "app:dd-github-action, env=PoC"

#      - name: Check outputs
#        run: |
#          test "${{ steps.selftest.outputs.myOutput }}" == "Hello"
